let data=[],mode='study',queue=[],i=0,stats=JSON.parse(localStorage.getItem('anatomyStats')||'{"seen":{},"right":0,"total":0}');
const $=s=>document.querySelector(s);
fetch('muscles.json').then(r=>r.json()).then(x=>{data=x;updateStats()});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));
$('#back').onclick=()=>{$('#cardScreen').classList.add('hidden');$('#home').classList.remove('hidden');updateStats()};
$('#reveal').onclick=()=>{$('#answer').classList.remove('hidden');$('#reveal').classList.add('hidden');$('#ratings').classList.remove('hidden')};
document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>rate(b.dataset.rating));
$('#resetStats').onclick=()=>{if(confirm('Reset all learning progress?')){stats={seen:{},right:0,total:0};save();updateStats()}};
function start(m){mode=m;queue=[...data].sort(()=>Math.random()-.5);i=0;$('#home').classList.add('hidden');$('#cardScreen').classList.remove('hidden');show()}
function field(m){if(mode==='origin')return['Where does this muscle originate?',m.origin];if(mode==='insertion')return['Where does this muscle insert?',m.insertion];if(mode==='action')return['What is its main action?',m.action];if(mode==='mixed'){let a=[['Name the highlighted muscle',m.name],['Where does this muscle originate?',m.origin],['Where does this muscle insert?',m.insertion],['What is its main action?',m.action],['Which nerve supplies this muscle?',m.nerve]];return a[Math.floor(Math.random()*a.length)]}return['Name the highlighted muscle',m.name]}
function show(){if(i>=queue.length){queue.sort((a,b)=>(stats.seen[a.id]?.score||0)-(stats.seen[b.id]?.score||0));i=0}let m=queue[i],f=field(m);$('#progress').textContent=`${i+1} / ${queue.length}`;$('#prompt').innerHTML=mode==='study'?`Study <strong>${m.name}</strong>`:f[0];$('#marker').style.left=m.x+'%';$('#marker').style.top=m.y+'%';$('#view').textContent=m.view+' view';$('#answer').innerHTML=`<h2>${m.name}</h2><div><b>Origin</b> ${m.origin}</div><div><b>Insertion</b> ${m.insertion}</div><div><b>Action</b> ${m.action}</div><div><b>Nerve</b> ${m.nerve}</div>${mode!=='study'?`<hr><strong>Answer to prompt:</strong> ${f[1]}`:''}`;$('#answer').classList.add('hidden');$('#ratings').classList.add('hidden');$('#reveal').classList.remove('hidden')}
function rate(r){let m=queue[i];stats.seen[m.id]??={tries:0,score:0};stats.seen[m.id].tries++;stats.total++;if(r==='known'){stats.right++;stats.seen[m.id].score+=2}else if(r==='hard'){stats.seen[m.id].score+=.5}else{stats.seen[m.id].score=Math.max(-3,stats.seen[m.id].score-1);queue.splice(Math.min(i+3,queue.length),0,m)}save();i++;show()}
function save(){localStorage.setItem('anatomyStats',JSON.stringify(stats))}
function updateStats(){let vals=Object.values(stats.seen),known=vals.filter(x=>x.score>=2).length;$('#studied').textContent=vals.length;$('#known').textContent=known;$('#accuracy').textContent=stats.total?Math.round(stats.right/stats.total*100)+'%':'—'}
